### ISSUE TITLE
build script support

### ISSUE THREAD

**Issue by TomasTomecek** [CentOS/container-index#197]
We would like to start building [our images](https://github.com/container-images) in your infrastructure. The issue is that it seems like it won't work because our github repositories contain source templates ([en example](https://github.com/TomasTomecek/tools/blob/5c571acc92a7e68be743809390c8caa450c96d86/Dockerfile.template)) and before building container images, we need to render them first. For that, we have a tool called [distgen](https://github.com/devexp-db/distgen).

After reading readme of this repo, I stumbled upon `Build Script (build-script)` which made me so happy and the feeling immediately vanished after reading `Currently unusable`. How difficult would be to implement it?

**Comment by bamachrn** [comment]
Hi @TomasTomecek , 
   current `build script` we are talking about here was meant for running `post-build` hooks developers want to run for checking things on recently built image.
 In your use case we need to render the templates before the build starts. that would not be much difficult. but let us get back to you on this. I have two points need from your side for this.
1. list of dependencies needed for rendering this.
2. is it possible to render these within a container or there is dependency on the base system.

**Comment by TomasTomecek** [comment]
We just need distgen and all of its dependencies (can be installed via PyPI):
  ```
  /usr/bin/python3
  python(abi) = 3.6
  python3-PyYAML
  python3-jinja2
  python3-six
  rpmlib(CompressedFileNames) <= 3.0.4-1
  rpmlib(FileDigests) <= 4.6.0-1
  rpmlib(PayloadFilesHavePrefix) <= 4.0-1
  rpmlib(PayloadIsXz) <= 5.2-1
  ```
It runs just fine in a container. Actually that's what we do in Docker Hub: we have [a custom build script](https://github.com/TomasTomecek/tools/blob/27ce1f4e14fe109dc8d1c72a6b93e1900e449b3f/hooks/pre_build) in there which renders the templates using 2 distinct containers. If we could run that script prior to build, that would be awesome.

**Comment by bamachrn** [comment]
Pre-build script feature does this. Cloned source repo can pre-processed using pre-build step provided by user. Entries for this has been added to container-index. Closing this issue will follow up on email thread about more image entries.
