### ISSUE TITLE
 Build-script needed for the userscpace containerisation

### ISSUE THREAD

**Issue by mkocka** [CentOS/container-index#200]
Hi all, 
[1] https://github.com/container-images/container-image-template
[2] https://github.com/devexp-db/distgen/

As you can find in [1] we are using a tool called distgen [2] for building correct Dockerfiles for each one of Fedora, CentOS or RHEL distributions. We would like to use CentOS CI pipeline for testing these images, but we need to be able to execute the distgen code in the beginning of the process to create correct Dockerfile. All the workflow information can be found in [1] and [2].

**Comment by mohammedzee1000** [comment]
Duplicate issue https://github.com/CentOS/container-index/issues/197

**Comment by bamachrn** [comment]
Pre-build support is implemented for this.
