### ISSUE TITLE
dotnet-* FAILED: Container build due to linter errors

### ISSUE THREAD

**Issue by tmds** [CentOS/container-index#217]
We are getting "FAILED: Container build" emails for dotnet-dotnet-20-centos7-latest, dotnet-dotnet-20-jenkins-slave-centos7-latest.

The logs are reporting linter errors.

_dotnet-dotnet-20-centos7-latest_
```
INFO: There is no 'EXPOSE' instruction. Without exposed ports how will the service of the container be accessed?. 
Reference -> https://docs.docker.com/engine/reference/builder/#expose
```

=> dotnet-dotnet-20-centos7-latest does indeed not have an EXPOSE, it's base image dotnet-dotnet-20-runtime-centos7-latest has the EXPOSE.

_dotnet-dotnet-20-jenkins-slave-centos7-latest_
```
INFO: There is no 'EXPOSE' instruction. Without exposed ports how will the service of the container be accessed?. 
Reference -> https://docs.docker.com/engine/reference/builder/#expose


INFO: There is no 'CMD' instruction. None. 
Reference -> https://docs.docker.com/engine/reference/builder/#cmd
```

=> The jenkins slave has no EXPOSE and CMD instruction. This is similar to the other Jenkins slaves (e.g. jenkins-slave-maven-centos7).

These are false linter errors. Can we do something about this?

CC @mohammedzee1000 @omajid @jerboaa

**Comment by jerboaa** [comment]
Not sure this is the actual reason why the job failed. I'm also seeing these:

    [2017-10-23 22:03:34,756] dockerfile-linter p5826 32 ERROR - OpenShift is not able to delete project: dotnet-dotnet-20-jenkins-slave-centos7-latest
    [2017-10-23 22:03:34,763] dockerfile-linter p5826 82 WARNING - Dockerfile Lint check command failed
    [2017-10-23 22:03:34,770] dockerfile-linter p5826 139 WARNING - Dockerfile Lint check failed
    [2017-10-23 22:03:34,774] dockerfile-linter p5826 140 ERROR - exceptions must be old-style classes or derived from BaseException, not NoneType

**Comment by mohammedzee1000** [comment]
@jerboaa @tmds thanks. We will look into the same and get back asap

**Comment by jerboaa** [comment]
@mohammedzee1000 Thanks!

**Comment by tmds** [comment]
Probably related to this, there is no dotnet-20-jenkins-slave-centos7 at [registry.centos.org](https://registry.centos.org/repositories/40)

**Comment by jerboaa** [comment]
@tmds I've seen the same error for `dotnet/dotnet-20-centos7` for which there is one at registry.centos.org:

    [2017-10-20 16:13:56,586] dockerfile-linter p5826 32 ERROR - OpenShift is not able to delete project: dotnet-dotnet-20-centos7-latest
    [2017-10-20 16:13:56,594] dockerfile-linter p5826 82 WARNING - Dockerfile Lint check command failed
    [2017-10-20 16:13:56,599] dockerfile-linter p5826 139 WARNING - Dockerfile Lint check failed
    [2017-10-20 16:13:56,602] dockerfile-linter p5826 140 ERROR - exceptions must be old-style classes or derived from BaseException, not NoneType

Not sure why it's `dotnet-dotnet-20-centos7-latest` and not `dotnet/dotnet-20-centos7:latest` in the error message.

**Comment by mohammedzee1000** [comment]
@jerboaa @tmds That is one of reasons why we take appid, job d and desiredtag seperately. Basically, for each container, a project gets created on jenkins, and the project name follows the pattern appid-jobid-desiredtag. This is done as the normal container name format is not allowed as a jenkins project name,

**Comment by bamachrn** [comment]
@jerboaa @tmds there was a bug in the code and it was failing to delte the openshift projects as expected. we have fixed it and deployed. that should not come in again.
For the dockkerfile-linter errors we are matching the best practices of dockerfile writing. let us look into that to avoid false alarms.

**Comment by tmds** [comment]
> @jerboaa @tmds there was a bug in the code and it was failing to delete the openshift projects as expected. we have fixed it and deployed. that should not come in again.

:+1: 

> For the dockkerfile-linter errors we are matching the best practices of dockerfile writing. let us look into that to avoid false alarms.

The jenkins maven slave would generate the same errors as ours (https://github.com/openshift/jenkins/blob/master/slave-maven/Dockerfile).
Are these errors filtered by the pipeline build? Or do the maintainers also get emails?

Can you trigger a build for dotnet-20-jenkins-slave-centos7 (so it becomes available at registry.centos.org)?

**Comment by bamachrn** [comment]
@tmds there was an issue in the notification service, we are working to fix that, dotnet-20-jenkins-slave-centos7  is avaialbe in registry.centos.org now

**Comment by tmds** [comment]
Thank you @bamachrn!
