### ISSUE TITLE
Docker build path cannot be different than Dockerfile directory

### ISSUE THREAD

**Issue by hhorak** [CentOS/container-index#220]
Hi, we have a bit different structure of the repository at https://github.com/sclorg/mariadb-container/, where we have basically:
 * Dockerfiles in the subdirectories
 * some other files in root directory

So, when building an image, we need to run something like:
```
docker build -f 10.2/Dockerfile .
```

That also means that more packages share the root directory, so `cccp.yml` cannot be in the root directory, because we cannot have one `cccp.yml` for more images. So, as I understand, this layout is basically not supported by the CentOS Pipeline.

**Comment by mohammedzee1000** [comment]
@hhorak thanks for reporting this. We will look into this in the coming week, and figure out a solution.

**Comment by mohammedzee1000** [comment]
@hhorak https://github.com/CentOS/container-pipeline-service/pull/365 I have opened a PR to fix this, once this is done, you will want to move the cccp.yml back alongside the dockerfiles, change git-path back to path of dockerfile, and instead use key `build-context` to specify the build context

**Comment by bamachrn** [comment]
This is fixed, we have a custom-build context support now.
