### ISSUE TITLE
Use .yaml instead of .yml

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-index#249]
`.yml` is used for historic reasons due to windows (only allowing three-character extensions)

`.yaml` should be the standard file extension across all files.

See the official yaml site for official ruling: http://www.yaml.org/faq.html

**Comment by mohammedzee1000** [comment]
@cdrage thanks for bringing this up. The pipeline itself is programmed to check files with extensions y*ml so it should be an easyfix.

**Comment by kbsingh** [comment]
+1 we can use .yaml but cant break existing content

**Comment by bamachrn** [comment]
This is updated and incorporated in the index-reader.
