### ISSUE TITLE
9 cccp.yml files don't match the job-ids in the Index

### ISSUE THREAD

**Issue by bstinsonmhk** [CentOS/container-index#25]
We should get these worked out before we enable pr-level testing in ci.centos.org (#6). 
See the output of a run over the master branch of the index here:
https://ci.centos.org/job/cccp-container-index/4/consoleFull

/cc: @mohammedzee1000

**Comment by mohammedzee1000** [comment]
@bstinsonmhk i believe this shouldnt be a problem anymore now that the reworked testindex script no longer worries about matching the job id. Although we should consider how we are going to do this in the future especially for entries related to multiple dockerfiles in the same directory, building different containers.

**Comment by mohammedzee1000** [comment]
This issue should be closed at it was solved long time ago.
@bamachrn ^

**Comment by kbsingh** [comment]
@bamachrn @mohammedzee1000 is this still an issue ?
