### ISSUE TITLE
Remove all references to Nulecule / Atomic App

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-index#262]
Nulecule + Atomic App are dead / unmaintained projects (https://github.com/projectatomic/nulecule and https://github.com/projectatomic/atomicapp).

**Comment by kbsingh** [comment]
Its interesting how much of the world is now gyrating towards solving the same problems that these things did, a few years ago. However, for now it does look as if we should drop references. We dont support them in the pipelines either.

**Comment by mohammedzee1000** [comment]
This issue has been fixed. Closing the same.
