### ISSUE TITLE
projectatomic/cri-o needs version tags

### ISSUE THREAD

**Issue by phemmer** [CentOS/container-index#316]
The registry image at [registry.centos.org/projectatomic/cri-o](https://registry.centos.org/projectatomic/cri-o) needs version tags.
Currently the openshift-ansible installer is pulling down `registry.centos.org/projectatomic/cri-o:latest`. With the recent release of cri-o version 1.0.0-rc.0, this is causing breakage as it is not compaible with OpenShift 3.9 / Kubernetes 1.9 <sup>*(ref https://github.com/containerd/cri/issues/619)*</sup>. However it is not possible to specify a tag for OpenShift to pull down because all the tags appear meaningless:
```
ZTY2NjdhZmZjN2
YjBkY2VkOGRmMz
MDEyNjQzNWQwMz
NjlkYWI2NjJiYW
NjcwM2VjYjBkOG
...
```

I already opened an issue over at https://github.com/openshift/openshift-ansible/issues/7708, but until we get tags we can use, I don't think there is a way to address the issue.

I'm not sure if this issue belongs here, or over at [kubernetes-incubator/cri-o](https://github.com/kubernetes-incubator/cri-o). But looking at the instructions on how to use the container index build system, I don't see a way for the upstream project to specify a tag per-build. It looks like the tag is only controlled via the `desired-tag` parameter in `index.d`.
Perhaps the build system could be configured to look for a specific label in the generated image, and use that as additional tags.

**Comment by bamachrn** [comment]
@phemmer for the random tags, we have fixed it with automated cleanup. you meant we do a `desired-tag` from container-index and another from dockerfile LABEL? why we cant add the desired-tags in container-index for all the different versions.

Because any image in registry.centos.org should have one entry in container-index otherwise they are going to get wiped off automatically.

**Comment by bamachrn** [comment]
This is fixed we are no longer pushing extra tags to registry.centos.org.
