### ISSUE TITLE
Change git URL for registry.centos.org/minishift/dnsmasq 

### ISSUE THREAD

**Issue by LalatenduMohanty** [CentOS/container-index#322]
The current git URL for `registry.centos.org/minishift/dnsmasq` is `git-url: https://github.com/gbraad/dockerfile-dnsmasq` and we want to change it to `https://github.com/minishift/dockerfile-dnsmasq-centos`. Is this possible? 
cc @gbraad 

The initial changes were merged as part of https://github.com/CentOS/container-index/pull/299

**Comment by bamachrn** [comment]
yes, a PR with updating `https://github.com/CentOS/container-index/blob/master/index.d/minishift.yaml#L5` would do the need full. pipeline will automatically take it once PR is merged. This makes more sense to me, as we are building the image under `minishift` namespace, it is better to have the source repo from the `minishift` project.

**Comment by gbraad** [comment]
merged now...
