### ISSUE TITLE
UI is down

### ISSUE THREAD

**Issue by sonnyp** [CentOS/container-index#410]
https://wiki.centos.org/ContainerPipeline states

> You can view the full list of containers available on the UI of the registry being served on https://registry.centos.org. 

But https://registry.centos.org ends up in 404.

**Comment by bamachrn** [comment]
Hi @sonnyp thanks for raising. we are in middle of migrating the service, UI should be back by this weekend. There is no issue in image pulls from registry.

**Comment by bamachrn** [comment]
Hi @sonnyp we got the registry UI back. we are still working on few issues with the image build process to get it fully functional

**Comment by sonnyp** [comment]
many thanks!
