### ISSUE TITLE
"latest" CentOS image version differs between CentOS Container Registry and Docker Hub

### ISSUE THREAD

**Issue by mavit** [CentOS/container-index#413]
I'm not sure if this is the correct place to report this, but the following was not what I expected:

```bash
$ podman run -i docker.io/centos:latest cat /etc/redhat-release
CentOS Linux release 8.3.2011
$ podman run -i registry.centos.org/centos:latest cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
```

Is this a bug?

**Comment by navidshaikh** [comment]
Thank you for reporting this!

@bamachrn I think we should re-point `latest` tag to the centos8 image?

https://github.com/CentOS/container-index/blob/4f2c2bcafcd86db2e13f7e01478a1b4b1d1e0dda/index.d/centos.yaml#L9

@mavit: as general practice, I think we should avoid using `latest` tags and use explicit tags instead. 
Please use `registry.centos.org/centos:8` to get centos8 from registry, and here is the list of available tags for centos/centos https://registry.centos.org/centos/centos

**Comment by bamachrn** [comment]
@mavit we planned for updating centos:latest to centos 8 separately to makesure the dependent images are updated as required.
that's how it was intentional. I have now updated the latest tag to centos 8 and now it would be in sync with base image updates.
