### ISSUE TITLE
run the index validation script via ci.centos.org on github integration for each PR

### ISSUE THREAD

**Issue by kbsingh** [CentOS/container-index#6]
We should be running the validation script, since we have it already, for each PR - would make life a lot easier.

@bstinsonmhk is this something you can help with ?

**Comment by mohammedzee1000** [comment]
Dont forget to merge https://github.com/CentOS/container-pipeline-service/pull/1 before using this as there are feature adds and corrections.

**Comment by mohammedzee1000** [comment]
I can work with @bstinsonmhk on getting it in.

**Comment by mohammedzee1000** [comment]
I believe we have completed achieving this functionality now
@bstinsonmhk @kbsingh maybe we can close this issue.
