### ISSUE TITLE
CentOS base image name for other containers building on centos7

### ISSUE THREAD

**Issue by mohammedzee1000** [CentOS/container-index#64]
Many containers building on centos refer to it in the docker files as FROM centos or FROM centos:7 or FROM centos:centos7. All these names are typically based on docker.io/centos:tag, which basically pulls image as docker.io/library/centos:tag, library being the default namespace in docker registry/distribution for all images without a namespace.

Currently, we are building the centos container under the centos namespace, which is registry.centos.org/centos/centos:tag, which means simply adding registry.centos.org  to listed registries does not mean it will be used while building containers which reference the centos base image.

We are going to have to consider how er are going to go ahead with this.

**Comment by mohammedzee1000** [comment]
@bamachrn @kbsingh what do you guys think.

**Comment by kbsingh** [comment]
we need the default actions per namespace piece down the road - how we implement this would need to be planned and mapped out, and we'd need to speak through witht he registry folks as well. I think we should explore the story a bit further for now,

**Comment by mohammedzee1000** [comment]
@kbsingh sure. One thing i do know from experience though is if we tag a container with myregurl/container_name, and do a docker push on it, then it automatically lands up in myregurl/library/container_name. and can hence be pulled as myregurl/container_name

**Comment by bamachrn** [comment]
This is implemented, we do have [library namespace](https://github.com/CentOS/container-index/blob/master/index.d/library.yaml) now. Images in this file get pushed without app-id. So the base images are accessed like `registry.centos.org/centos:latest`
