### ISSUE TITLE
Supporting builds for containers no longer supported by upstream

### ISSUE THREAD

**Issue by mohammedzee1000** [CentOS/container-index#71]
Considering how we have continuously encountered possibility of containers no longer being supported by upstream, but having the requirement that they be available on registry.centos.org for sake of existing systems not breaking, we need to figure out strategies on how we are going to handle this.

First, considering builds, there must be a way to stop containers from being rebuilt, as is the case with openshift origin. There might be other reasons as well, why a user might not want container to build for shorter duration as well. 

Maybe we can have a build switch that will allow builds to be turned on and off such as "build: True" or False and based on its value, the containers will no longer need to build. Of course, we will have to be careful about accepting PR's which turn builds off, requesting user to provide reasoning why they are disabling the build and expected time they will be back on (unless its permanent disable - in preparation for future purge)

Of course, we should also have a flag that marks a container as deprecated at some point as well. 

This also brings us one more problem as to how we are going to keep the said containers on registry and on the index as well. We should figure out a strategy as to how we are going to get the containers back on registry in case of failures. 

One last thing is figuring out a purge strategy. How we are going to periodically clean out deprecated containers, both from the registry as well as the index.

**Comment by mohammedzee1000** [comment]
@kbsingh @bamachrn @dharmit @navidshaikh @rtnpro thoughts?

**Comment by kbsingh** [comment]
i dont understand the problem.

once we build something, its there - its done. If upstream does not update anything, that just means the tag's and the builds are not impacted in the already built containers.

what am i missing ?

**Comment by mohammedzee1000** [comment]
Yes and in most cases, they should not affect builds.

But for cases like origin and possibly more, instead of stopping builds by hacking into prod, we should be able to disable builds from the index. Also, there might be other reasons why a build might need to be disabled temporarily. Of course, we will be questioning them why they need the build to be disabled before allowing the same to happen.

Also, that is not the only thing brought up here. There is also the case of marking containers which are no longer supported as deprecated, so users get enough time to move on.

Another thing is housing the source of the containers no longer being maintained. Its possible that upstream may no longer want to house the source of the deprecated containers. So we will have to house the source ourselves, or the links in the wiki page will break, or at the very least will point to something that may not be valid.

Also, we should ensure the contents of the registry are backed up properly.

Again, just thoughts here

**Comment by bamachrn** [comment]
This is default case, any image pushed to registry.centos.org is never removed. We will not update the images if it is removed from index-entry
