### ISSUE TITLE
rabbitmq image not on container index

### ISSUE THREAD

**Issue by surajssd** [CentOS/container-index#78]
centos dockerfiles repo has [rabbitmq artifacts](https://github.com/CentOS/CentOS-Dockerfiles/tree/master/rabbitmq/centos7) but image not on index.

**Comment by mohammedzee1000** [comment]
@surajssd thanks for the information, i will look into this right away

**Comment by mohammedzee1000** [comment]
PR raised for appropriate cccp.yml https://github.com/CentOS/CentOS-Dockerfiles/pull/107

**Comment by surajssd** [comment]
@mohammedzee1000 thanks for quick action

**Comment by surajssd** [comment]
since https://github.com/CentOS/container-index/pull/80 is merged I will close this!
