### ISSUE TITLE
[UX?] Why the names job-id and app-id?

### ISSUE THREAD

**Issue by containscafeine** [CentOS/container-index#92]
Hey guys,

Any idea why were the fields named `job-id` and `app-id`? Why not something like `container_repo` and `container_name`?

I didn't find it to be very intuitive, was just curious on why is it this way?

**Comment by kbsingh** [comment]
an app can have multiple jobs' and jobs can setup their own relationships. the build targets are not limited per se to a specific container or a repo.

**Comment by containscafeine** [comment]
@kbsingh the documentation (README) indicates none of this behavior about relationships and multiple jobs, and as an end user this mapping does not feel natural at all.

Also, this terminology is not used anywhere else in the container ecosystem, and container index caters to that audience.

app-id - container repo
job-id - container name

these mappings seem super foreign to me, and each time I need to refer to the documentation while talking about this.

This was just a feedback as an end user, just putting it out :)
